All tasks

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,11 +1,32 @@
 #!/usr/bin/env bash
-# Script that configures a new Ubuntu machine to respect above requirements
+# Install and setup new nginx server
 
-sudo apt-get update
-sudo apt-get install -y nginx
-
-echo "Hello World!" | sudo tee /var/www/html/index.html
-string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
-sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
-
-sudo service nginx restart
+apt-get update -y && \
+apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    service nginx start
+    echo -e \
+"http {
+    root /var/www/holberton;
+    server {
+        listen 80;
+        server_name pearmountain.space;
+        rewrite ^/redirect_me/? \
+https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
+        location / {
+            index index.html;
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/holberton
+    echo "Holberton School" > \
+	/var/www/holberton/index.html
+    service nginx restart
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
